apiVersion: v1
kind: ResourceQuota
metadata:
  name: memory-lab-quota
  namespace: memory-lab
spec:
  hard:
    requests.cpu: 100m
    requests.memory: 128Mi
    limits.cpu: 500m
    limits.memory: 256Mi
    pods: "4"
