package com.banklab.accounts;
import java.nio.charset.StandardCharsets; import java.security.*; import java.time.Instant; import java.util.*; import javax.crypto.Mac; import javax.crypto.spec.SecretKeySpec;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class AuthService {
 static final String COOKIE_NAME="moura_session"; private final AccountRepository repo; private final AccountService service; private final BCryptPasswordEncoder bcrypt=new BCryptPasswordEncoder(12); private final SecureRandom random=new SecureRandom(); private final byte[] key;
 AuthService(AccountRepository r,AccountService s){var secret=System.getenv("BANKING_SESSION_SECRET");if(secret==null||secret.length()<32)throw new IllegalStateException("BANKING_SESSION_SECRET must have 32 characters");repo=r;service=s;key=secret.getBytes(StandardCharsets.UTF_8);}
 @Transactional public Account register(String owner,String password,java.math.BigDecimal balance){password(password);String number;do{number="%08d".formatted(random.nextInt(100_000_000));}while(repo.existsByAccountNumber(number));return service.create(number,owner,bcrypt.encode(password),balance);}
 @Transactional public String login(String number,String password){var a=repo.findByAccountNumber(number.replaceAll("\\D","")).orElseThrow(InvalidCredentialsException::new);var now=Instant.now();if(a.isLocked(now))throw new AccountLockedException();if(!a.hasCredentials()||!bcrypt.matches(password,a.getPasswordHash())){a.loginFailed(now);throw new InvalidCredentialsException();}a.loginSucceeded();return issue(a.getId(),now.plusSeconds(900));}
 @Transactional(readOnly=true) public Account authenticate(String token){var id=validate(token);return repo.findById(id).filter(Account::hasCredentials).orElseThrow(UnauthorizedException::new);}
 private String issue(UUID id,Instant exp){var p=id+"."+exp.getEpochSecond();return p+"."+sign(p);}
 private UUID validate(String token){try{var p=token.split("\\.");if(p.length!=3)throw new UnauthorizedException();var raw=p[0]+"."+p[1];if(!MessageDigest.isEqual(sign(raw).getBytes(),p[2].getBytes()))throw new UnauthorizedException();if(Instant.ofEpochSecond(Long.parseLong(p[1])).isBefore(Instant.now()))throw new UnauthorizedException();return UUID.fromString(p[0]);}catch(Exception e){throw new UnauthorizedException();}}
 private String sign(String p){try{var m=Mac.getInstance("HmacSHA256");m.init(new SecretKeySpec(key,"HmacSHA256"));return Base64.getUrlEncoder().withoutPadding().encodeToString(m.doFinal(p.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private static void password(String p){if(p==null||p.length()<10||p.length()>72||!p.matches(".*[A-Za-z].*")||!p.matches(".*\\d.*"))throw new InvalidTransferException("password must have 10 to 72 characters, including letters and numbers");}
}