loki:
  auth_enabled: false

backend:
  replicas: 1

read:
  replicas: 1

write:
  replicas: 1

gateway:
  enabled: false

loki:
  persistence:
    enabled: true
    storageClassName: local-path
    size: 20Gi