apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  resource.customizations.ignoreDifferences.apiextensions.k8s.io_CustomResourceDefinition: |
    jqPathExpressions:
      - '.metadata.labels | select(. == {})'
  resource.customizations.ignoreDifferences.kyverno.io_ClusterPolicy: |
    jsonPointers:
      - /status
