apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [namespace.yaml, tempo.yaml, otel-collector.yaml, grafana-datasource.yaml, dashboard-configmap.yaml, prometheusrule.yaml]
configMapGenerator:
  - name: tempo-config
    namespace: tracing
    files:
      - tempo.yaml=tempo-config.yaml
