apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-producer
  namespace: workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-producer
  template:
    metadata:
      labels:
        app: cpu-producer
    spec:
      containers:
        - name: cpu-producer
          image: ghcr.io/gefmoura0601-bot/cpu-producer-go:1e78b4a
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: workers-rabbitmq
                  key: RABBITMQ_URL
            - name: QUEUE_NAME
              value: cpu-jobs
            - name: MESSAGE_COUNT
              value: "80"
            - name: MESSAGE_PREFIX
              value: "cpu-job"
            - name: MESSAGE_DELAY_MS
              value: "10"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
