server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  charset utf-8;
  charset_types text/css application/javascript application/json;

  location = /healthz { access_log off; return 200 "ok\n"; }
  location /banking/ { try_files $uri $uri/ /banking/index.html; }
  location = / { return 302 /banking/; }

  add_header X-Content-Type-Options nosniff always;
  add_header X-Frame-Options DENY always;
  add_header Referrer-Policy strict-origin-when-cross-origin always;
  add_header Content-Security-Policy "default-src 'self'; style-src 'self'; font-src 'self'; connect-src 'self'; img-src 'self' data:; object-src 'none'; frame-ancestors 'none'" always;
}
