import{FormEvent,useEffect,useState}from"react";import{api,money}from"./api";import type{Account,DirectoryEntry,Transaction}from"./types";
const KEY="moura-banking-transactions";
export function App(){const[account,setAccount]=useState<Account|null>(null),[directory,setDirectory]=useState<DirectoryEntry[]>([]),[transactions,setTransactions]=useState<Transaction[]>([]),[mode,setMode]=useState<"login"|"register">("login"),[view,setView]=useState<"home"|"transfer"|"history">("home"),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
async function load(){try{const me=await api.me(),dir=await api.directory();setAccount(me);setDirectory(dir.filter(x=>x.id!==me.id));const ids=JSON.parse(localStorage.getItem(KEY)??"[]")as string[];const items=await Promise.allSettled(ids.map(api.transaction));setTransactions(items.flatMap(x=>x.status==="fulfilled"?[x.value]:[]));}catch{setAccount(null)}finally{setBusy(false)}}
useEffect(()=>{void load()},[]);
async function authenticate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);try{const a=mode==="login"?await api.login(String(d.get("accountNumber")),String(d.get("password"))):await api.register(String(d.get("ownerName")),String(d.get("password")),Number(d.get("initialBalance")));setAccount(a);setMessage("");await load()}catch(x){setMessage((x as Error).message)}}
async function transfer(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!account)return;const f=e.currentTarget,d=new FormData(f);try{const t=await api.transfer(account.id,String(d.get("destination")),Number(d.get("amount")),String(d.get("description")));const ids=JSON.parse(localStorage.getItem(KEY)??"[]")as string[];localStorage.setItem(KEY,JSON.stringify([t.id,...ids].slice(0,20)));setMessage("Transferência concluída.");f.reset();await load();setView("history")}catch(x){setMessage((x as Error).message)}}
if(busy)return <div className="loading">Abrindo Moura Banking…</div>;
if(!account)return <main className="auth"><section className="login-card"><div className="brand auth-brand"><span>M</span><div><strong>Moura</strong><small>Banking</small></div></div><p className="eyebrow">BANCO DIGITAL DO LAB</p><h1>{mode==="login"?"Acesse sua conta":"Abra sua conta"}</h1>{message&&<div className="notice">{message}</div>}<form className="form" onSubmit={authenticate}>{mode==="register"&&<><label>Titular<input name="ownerName" maxLength={120} required/></label><label>Saldo inicial<input name="initialBalance" type="number" min="0" step=".01" required/></label></>} {mode==="login"&&<label>Número da conta<input name="accountNumber" inputMode="numeric" pattern="[0-9]{8}" required/></label>}<label>Senha<input name="password" type="password" minLength={10} maxLength={72} required/></label><button>{mode==="login"?"Entrar com segurança":"Criar conta"}</button></form><button className="switch" onClick={()=>{setMode(mode==="login"?"register":"login");setMessage("")}}>{mode==="login"?"Ainda não tenho conta":"Já tenho uma conta"}</button><small className="security">Sessão protegida e expira após 15 minutos.</small></section></main>;
const nav:[typeof view,string][]=[["home","Minha conta"],["transfer","Transferir"],["history","Histórico"]];
return <div className="shell"><aside><div className="brand"><span>M</span><div><strong>Moura</strong><small>Banking</small></div></div><nav>{nav.map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{label}</button>)}</nav><button className="logout" onClick={async()=>{await api.logout();setAccount(null)}}>Sair</button></aside><main><header><div><p>CONTA DIGITAL</p><h1>{nav.find(x=>x[0]===view)?.[1]}</h1></div><span>Conta {account.accountNumber}</span></header>{message&&<div className="notice">{message}</div>}{view==="home"&&<><div className="hero"><div><p>SALDO DISPONíVEL</p><strong>{money(account.balance)}</strong><span>{account.ownerName}</span></div><div className="monogram">MB</div></div><div className="stats"><article><span>Número da conta</span><strong>{account.accountNumber}</strong></article><article><span>Transferências</span><strong>{transactions.length}</strong></article><article><span>Status</span><strong>Ativa</strong></article></div></>}{view==="transfer"&&<section className="narrow"><form className="card form transfer" onSubmit={transfer}><p className="eyebrow">PIX INTERNO</p><h2>Nova transferência</h2><label>Destino<select name="destination" required defaultValue=""><option value="" disabled>Selecione a conta</option>{directory.map(x=><option key={x.id} value={x.id}>{x.ownerName} · {x.accountNumber}</option>)}</select></label><div className="row"><label>Valor<input name="amount" type="number" min=".01" step=".01" required/></label><label>Descrição<input name="description" maxLength={140} required/></label></div><button>Confirmar transferência</button></form></section>}{view==="history"&&<section><div className="title"><h2>Suas transferências</h2></div><div className="table card">{transactions.map(t=><div className="tr" key={t.id}><span><b>{t.description}</b><small>{t.id.slice(0,8)}</small></span><span>{money(t.amount)}</span><span><em className={t.status.toLowerCase()}>{t.status}</em></span><span>{new Date(t.createdAt).toLocaleString("pt-BR")}</span></div>)}{!transactions.length&&<p className="empty">Nenhuma transferência nesta sessão.</p>}</div></section>}</main></div>}
