apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpa
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://github.com/gefmoura0601-bot/k8s-lab-vmware.git
    targetRevision: main
    path: kubernetes/platform/vpa/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
