---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: banking-session
  namespace: banking
spec:
  encryptedData:
    session-secret: AgAbhLA3nLvHtf417s9oCJAsoELqVZtWB5QBR3jbvNN1B+pM/5B+6ryToxyq8USLXjAZKfJjMznJ/IteookwNEAU9j5Wu0NF2oSrUQiv7o1Sk2JBHXS+6U/4TwRczXqiIMKNCaVphfYUGrQE34csRBFdz+ByFK+xZUGIfswAoFE5SZPiBWJtdHPAYGC0xwhk+pVzfsqtzUB2vMXtCpR5j92BYGWjPt9XbfGCvouShJxvSYsJPAoE8gjm6j6593t4aHqyi24tj/JNrqykbHS5MIW0OjdRoOl4eePi0au50wRnNbLkkkto7heEETsFf702X887dIqVHoQ03BAmYQl0GQ2IpNC0nuLU/LNMYkqBScMu8eeKwf2qBAv56SqOOKNDbgrxSg5RXgIZ9jxMERD0t+s0WDKkR9QBv/RZAvmKkOFuwcm9JaR/aPutFkOxVKkk86SkawnDB08FO0i9xOvZTuQb0RK/qHYgmSxNWdJSfIlhTF13hkvLhziMKT0h3RrMP26BmOd4UOazpZcTE9NidZs90MW1BaPEI78TXt44CKjDPi6uDGITaeToxAFCpyItAU+7/pdhkWUGyO2+F67O9ADG2QJT3bFnCxj3kPTUsrJNsvQG2s6RYvJLF17G+87P0/AyltdqhwPUi2s5Uq7cEJn8bhlXaW1UaLlnhK55jM5qpIkzUeWpCVN15+VV14v1FVtViYM3tbA9+A0U8uUamjD1OAW7Z+IRJvsr8oL39WRckFoBnIreVoGm7w0TbvQzzhUzH+wXBAm/NQmqjO91Q0FZ
  template:
    metadata:
      name: banking-session
      namespace: banking
