---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: banking-e2e-db
  namespace: banking
spec:
  encryptedData:
    password: AgCWjRGxyvMB0RW5YTFMNbQwazMemFXtOmOTJfJDh/4/Dk2KBeaygCJ+qGK3j8xbMZP9TKYFQBamFCkX42eFZr9+KKHX55mI+dvf20wShErnP7cWcIZxqa2VCP2xnRyhXG6PJfr0Th+vMZHqFhgt4A44j+l+9WGyqv0fce2dAwX52qaSHuiWZ86mmfbW3DvF5G2pYzbFOrPBOVgHYzmTif8CXJu0W97YX14wT2HEHZGCutITbNw9L/uXef68cCzhnY57T5KW3lkU8WnMXqV7gmgpmX+XvXCSNL1KGzh5cj5LaVVrzcDeyD4HPJOb2wsseb8XQIbIZsB4Z9YZWeqToALJDQr2czFvp1sCP+WwD242zTzSnYwamuIq40jVeUXYl3zFLxcjJeZaXTM2mIOiqFUxiet7Syg4GffPKn+8hz4Kt/kusrfDbLXmoSJfKP1YIAd5+/FkR9fZCMoKmjc32CwUgrIPMR9/526Ri+hJzHZJMGAszzIAqdZo8gIbs19wBV4vE14lXlLbZAJ0cTSQBNeXJdz4fOYG0HiQS+fx3ffRCgiqQsrSnrK+jwl4MIIj6aqDjs5D86amWpmH8ZLdvQ3XrHsyQi3li/SNuqrpBCFqlGE50DHda2Xj8EwiHYo2Cz77BpkzyEmx9wZljJGqKsXKKGgwSlfO2oaYnRq5ik4tZTawjjBfoDRNPLPDCFwnPhq0p6qIMq+mUnn5hjrSq/cP0+Y/10vSXoYaVZQsB1Cgt0U1yMiiuy5WBPgd
    username: AgA2rydijBLKEmWj8l7c5roeiKurnKHaceDkke+6laFwdxfbTGdZOLrwFrjFNiXMaPzIyiKNVOz63ob2VTZC32s1w5ZMOU4/80Ja6CFuyZiW1rASwMkL4t6i0vxAKk1atBT27eAhFn2UvB2DBbxeYcqYNiRPQgv7D/RvXvtXDDBcGxZvVK0GBMgkT+y7zCT/3QqKWvSpEyUM87RnO3PFvz0z16NNj3ZuCYTj6Az/IpM2QtVzBO/sGioXMUOoZ4SnjqWk5l+he5RplhqtkNhLbAoAF+KEVPjbWedf+4mcf7F/8mjNyOZlBRIDrZwg9d10chuf2X9GugMzTE/NIvRojwPNXh+lqa2p+aMfhRtNQ2CMo7QcOfXPWM3wHPpU7yBQTRCTj/9DwsvEFFOYn1PQp6wxUgu7lYdlyT344LHS07r1g2On9vs0c34MmaE3smpXrbtL4bqhCzPmGJxDC4sxM0fpanQDYS9q5dQG+JE597757dNFZxT+Ciro9s/rxgNF/gFn14UYJQ1vaJswxgyZUIXtVeiDx1TBrthlKgYkCvkjyL88cmD6s5w7VI/dXXAZB4KhTJxnQzgJy+Csq2JRC+Glyj/lh7Jg5IfG7dC02CWJ02Op3rgC0+S0FSEP+lxJl5f3OW/IoTZ4ZND0INVelyeSST/0E6mYnE4jyWHqEGIXEEy4m99DknBa4QA/w77bf1sL0GXKE93m04ujww==
  template:
    metadata:
      name: banking-e2e-db
      namespace: banking
