apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: banking
spec:
  encryptedData:
    .dockerconfigjson: AgDWtrMbTnAUAvKpBi9QzzQpAVtQxEGrRFQfC7rO1tydZRa+bnEfrp0oB0unVsqetZ8FmYDiuzzt9eYKBTsNhZ0MUghg7Q+kUdgtFQ+Yx6mchLDoUWXIJTE2kNMPRYRBLxmxVvMbuc+jy4ffzm3IIqPBr6IoAtQcmzqq45jY3s/4zHqNfBQ7DTBE01AOaQqQ9O7bL10zLX97nljvZY2lgtSlMehihpBb4GY8S16t9gpIu+JRyUPrvk31QzzX9NVI/mBAkDZqqwA+jX82tqQfAc5w/o34wXBUs/yCGI8YKMkX3v1Bmut7rvESAnt6tSJFGiyA9L5PPT0omel73361BfTxTLuC7GCjVqCYDVX+hxIgtfjP2g0V9MpROdjhvbAw6Icpiov34esH3Oi/csGv/kBe0eR5IknBvkcwUOTv/3zGQsgOBpvuo9+jwsuxPigaIUrvTln7F8oWMTzg5rYWehhWR4sBuMbBkX1eJYjE88HV481Xl9Uz9zPKirWVB7ENVuUtXJnVCALIQQ1ZbiXtxtflX9IliQgTWiE3OSJBDdwgPOTALLZnBK+5+X+TyF3pRi0k/T/qSkz/ZzkSdunSbGk0zqt4xaz61T/AqbtU7VVqMR0Yz4/v4/M9hVVJQl4sbfci1W+FQtITckN67ucM4tCPUzpM40cpsqCI+/O8hgV8M8YmLni9PEanm52Q1ozjTIz5UfMkAFZJsRxnRa92huUpsmRGFpoXnlDFKyuc3r38hIEtuUuASsi7aYPxLW79hzEPI3VS4rHr2wHbqdw+iPT46JM9IrWUBlHoxzNAMTL8G1cD9Gr2bSSr9cnCpns07wnvaReaDE2iaShVqzp2Kv/YS4paY4X1uMFzkIYb48UQv5dDmg4un73JWJ5Q9GA3meorRjwNRncBlML3qyn7pjacYW+BNN9ZZQGlXztnlV4CBuMZMC5PhdLievN6HrYs9Q0n
  template:
    metadata:
      name: ghcr-secret
      namespace: banking
    type: kubernetes.io/dockerconfigjson
