apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: banking
spec:
  encryptedData:
    .dockerconfigjson: AgBlTAQABSYm+owOw7hM1f7TEMktwxgDu7b2dwis2CwSrtTFSRg9Am8oK4YgJAiAe4s8ntQ0Sl2LEucaQGo1cFobDKjKIypVOIbZzzl0r6ct0d3qTXrI1Nd1q+NN2MVEFEKAJZUONs0So4fAXcykrkt9FV72CzaURjLIsZibGlpVm8ER4C8C5bE9/lykDAf4j70vpdkKgYJkBNUGhK1nTOhYrZ20McFWpXpFzKigEqDjfwB5LH3p1Y4e63+NxuyGuAcL0H6Cp7eCluGWIhQanWFgSLQRFEc9YK0DK+05Y1Q/O16Yd21iubTKpcYXxCyS7EIZlBuQsPVPq5+Qokw1Etbc6XYshmI83pEzFsCt2VPIymM8NayaD+G0KO14QUfh9IVGPGT9PsP8J4KDDjuYP2MnAIZpnTajFqypgklgNNk1GOyuC83TvusRbCRgjm4xhBspVpyE1ceEShwFKH1Ain0dAH4oUq+oZ1pMvV43WhTiBAI0nQA6p4q7ea9bSbGZMykawLMWyu3KLP4jKqoi2tvO4hSyVScFDcnXC9W1xztw77wY1PvNGNLKS1VMMaxwpLxBUc8tDYG9xrKNuD0mzQy7tIRZQneEeQ3ZRk+37q1Wj8pRPCnxYgAI4y2hwhXFUTwl0wTWxWLcYVF/ob3A4Eik84W7WRR3bI5fZpf6IQ+WNj03xeZ/fxLIrmHYcNU10MaGPL3I35MeiMSATTCIRtUwGthiMiqoxtayqxjavtSDY/TqlhYx34S/7Pqh+4ZsF4L5bxWNrXpyjQvKOLHEwIhw0PWFGCajK/wxJB1IzY9OX8g2W+X1I1DJfzgrEy7UdsZPTerlvKSXscLVpZvgfmmzdoHzafjocdvI3Wb1Uvbi1I8qfBQ/0FLEHIJJpZGRgvGbVDzf5Xi9UtmYfxd0HSL3PTk2N/+uFmQZjoRjaat20Q/sKe5aXv1pfiKCgn0lI6a3
  template:
    metadata:
      name: ghcr-secret
      namespace: banking
    type: kubernetes.io/dockerconfigjson
