apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - banking-db-secret-sealed.yaml
  - banking-session-secret-sealed.yaml
  - ghcr-secret-sealed.yaml
  - account-service.yaml
  - transaction-service.yaml
  - banking-web.yaml
  - autoscaling.yaml
  - networkpolicies.yaml
  - istio.yaml
  - monitoring.yaml
  - runtime-dashboards.yaml
  - banking-web-dashboard.yaml

images:
  - name: ghcr.io/gefmoura0601-bot/banking-web
    newName: ghcr.io/gefmoura0601-bot/banking-web
    newTag: bc9db74
