apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-service
  namespace: banking
  labels:
    app: account-service
    team: banking
    environment: lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-service
  namespace: banking
  labels:
    app: transaction-service
    team: banking
    environment: lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: banking-web
  namespace: banking
  labels:
    app: banking-web
    team: banking
    environment: lab
