apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: banking
  labels:
    app: transaction-service
    team: banking
    environment: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: transaction-service
        team: banking
        environment: lab
    spec:
      serviceAccountName: transaction-service
      imagePullSecrets:
        - name: ghcr-secret
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: transaction-service
          image: ghcr.io/gefmoura0601-bot/transaction-service-dotnet:a59a30d
          imagePullPolicy: IfNotPresent
          env:
            - name: AccountServiceUrl
              value: http://account-service.banking.svc.cluster.local
            - name: ConnectionStrings__Transactions
              valueFrom:
                secretKeyRef:
                  name: banking-db
                  key: dotnet-connection-string
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /health/live
              port: http
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: 10
          resources:
            requests:
              cpu: 75m
              memory: 160Mi
            limits:
              cpu: 500m
              memory: 384Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1654
            runAsGroup: 1654
            capabilities:
              drop: [ALL]
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: banking
  labels:
    app: transaction-service
    team: banking
    environment: lab
spec:
  selector:
    app: transaction-service
  ports:
    - name: http
      port: 80
      targetPort: http
