apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vpa-tls-certs-sealedsecret.yaml
  - vpa-v1-crd-gen.yaml
  - vpa-rbac.yaml
  - admission-controller-service.yaml
  - admission-controller-deployment.yaml
  - recommender-deployment.yaml
  - updater-deployment.yaml
