---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: messaging
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgCzx1TLMfaOBEp+FG1PsX6xp3iya4rDudjVitRYvxn0Q15JfgCt/LWpwhffZU29MXNiX2GRuGVDysJ6yH6yatNfJmYXWYla6jRR2QYq4c++ID+oXG4Ta+xzlS7pizZ7G4v/lBeFmgU6ftxxtaq2IQ5UutG2v4529IEhSih/M2AnxLpoEgZJNaUQlZttiqxIdC9hM/J7XeCPFvlnYb9IwIm+H8lFcM1ya4BhA2CnqD/CtEGvX+YtEMYaMgcUTTBcdVkr8du4V1LlEEgKOJlOby+5ub7Eq5PGu0Oe45ZVpm8ZgvuHXKDgbcKJQ7PYxaAqcJ/XREWuh/eKdZ65rR9lGwUBFVnQ0R/1fhXJeSUBZXNNbmB+Vp1APgmqIfmaCI/ffcHQss/49A+DD33xhncNGa6gmvo7DbIX3FHlSBwIXdfo3gHF1B9UJDc1+7eIa2HxnO4G232WgoJi5Zg1/UWcfsttr6Pop0SPTkd8IPtx8Y0IaNiv8fmaSC4+VkgqWItU9UQP1aLGUzQ5ILE4o5NtEsbw09UHEZAAPR90f/STR8GXXga4ytM4wFUkG7jH/snig3Y71ZLeT+ka2SSRvnDnkmVSr1o6bodqE2E/Tw0ozDuC8fYhd8V0m5B5RNQZ04KZ/uukLMpk0W4/l2hLd9NfOWcSBOGSrre5MMr6G2cJ1hNDAlbpIQf5TLWE/EpCRv5rJSLK51l5aRWceQ==
    RABBITMQ_DEFAULT_USER: AgClqIFyvJ0QNUqMAg5MRe+sLMG9Lh4zv2qvgPlTNnTvcsFHwkVErcL3ji0vP+bRegjLDS6mRxFybb5iSyEhbZjEGqjJGRjYpwu3dYVUQGBFD/r1JWXDN8bU/FuFvK/mj1VF++wMhvIlcs5L/kKAnZLURds7m8SADb7iwcZKF1TkXzQKqdICKkNRJ8axEUBhFDNdS3E6d5/nNwQLYfT95f/fXqAR+sc3ZhhsxE77VmRJZQZ0d6REMnlqat7OMhHAZGxNm/wR98mzkOP/pTVyLBPsX/FxNDTLr3DAzw5rfLM7RMZSB77JynIXHsQBvNA4Us0cHdLOBW/gLFUywvg5Q1dOF9h+sPUrDMmYvdyi3BftMs1/FN3i3bN+Iecu42ywQRXEhqMfASJ8CVfHoqt8wPcDzPt/tZ3YeYI8tmnOS0WenU+KwXEtzWT8pxI0jTmgpowhUaR1ma681N1v0ury/KWoFjex2Tspbs7UUMJ1pnQQo0xCp8x6KpTKCtfS8WrjksMzRxXysh4sfIowd+nFEqnoDGj/bncWPuEqsZd+7gibb3ZNjNG3wiGKgNUYCwEmLucYPvao0fat/+i9wYJ9XW5Q5mFLOHl/CxiudQf6+FsQli4hZB6juKpMf6X5qWHY8NzcH5ktY3gfS/BYvQlbqHv8nqv0O6EMPtJGKglyPGgG7/GNhSpcVqD9SSVi3ruD3IZLYimFzQ==
  template:
    metadata:
      name: rabbitmq-secret
      namespace: messaging
    type: Opaque
