apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  namespace: messaging
  labels:
    app: rabbitmq
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: rabbitmq
  endpoints:
    - port: prometheus
      path: /metrics/per-object
      interval: 15s
      scrapeTimeout: 10s