---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: apps
spec:
  encryptedData:
    .dockerconfigjson: AgCjcDi96g6rGQw+fvutDUKgOMG/Njbh1T7LApFNkMoTtDNREPpgNqPHR8whuZ1MmS7a6eQ7vTrjwNByhmaBi4FAekiMFAnkXOzn5yNjPJqKnhTXX7Ig+gIEn37XpZvs27b/uGcMX736Kchs8SjV9WpZFpAng5icU5z+ovKzxRnli+JvCx7Ayd2IWE7vwFhpVj/2F3uVS0YIUoClRKITwNyzxMc7bRf5lF6XT36AgwA1n7IxCkx50hZDo904wfOFraQnxomWhKpcW3afxKif7oKvb9+NygyALrqk1Dw4T4YgBezBq9DklN9TWZv/Ch8HbfSL5DBgXTbO453ACO65l6VO9ajsKlzYmyxGnZuqt8NH/7Tb+eygkWL6ccvviwfp7bSuIL9t4IP3b4PrO5xX7Lg9LxAQY/LtstWedkD2v2bg3gVnCcKpMChOGWWM13yX2pW8Jpn8DCmz2Rx43U2qGhZCNOBlQy+z5XYG2/spsWc5xSVlI1VvOmpnYafddjV8pJMR8x8dfE8bZ/jjrayOqTlbEzbDb4D36PCEbobpQVO060SqWF6DlpxU5JfqrbArhfEZqTfZ6vwPmhIVvtbL3+PLo7A68mMNy2+gfnXxnwu0raQIPoXmeXZyEzvaHOlAyoJ817fHQBvKsmBPVM8HPxtEPbzTlNP8YobtBYW2E9ak4Ird643fPxuIM1MQ4Q8UMhHXe/ZSHBhbdK6VnvMj1KlQn7BVit0wl3ede8H/5S75YyWxdSlg4ORbJ3Ah+IsrgahRh1kWLzvZ7JSNJbzCMLK5XWuU/1QAIvmSK2Pn2kt9YVEOUEm8uGJcV5iVdYTheUSNbrknDmGDH6OUDVyYhttv9HSGE8fhpjcScf4Fz1Qj7kHrV1ctSJKkX71RuntvLCfeWiQpVTmSHhlucvExZY/AQe/xTH61KI7+n5EkMwKfh1MDRPRqvIMO4tBsqz5wolgdIxx+OrkVKhMjZz0hRdNh4JnpPutrjzNu3IZmNqDI/VrwX0BJ8eCkpjp/nHuPdF0aRblFFwi+pPkA3RQz3ogp9j8g91gYzpvN9ONRHypCUOfQv7izeE7t+6iRkSGdnuCNIc5KTcop00MjbHcZ3AfFRpHk+vdQy+auNE0DrAFX3xl7iiJ72DYpMDu3GNxIqB6DfU27UevmTWcytkzKaN4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: ghcr-secret
      namespace: apps
    type: kubernetes.io/dockerconfigjson
