apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: postgres-api-go
    newName: ghcr.io/gefmoura0601-bot/k8s-lab-vmware-postgres-api-go
    newTag: initial
