apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-api-secret
  namespace: apps
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgDNMYLwAjtFai7fOdZ0EdN6Xz9wLRHfB0GXz+NHOXMu86Io8aGO8MSb4fF6nSGfmBtV9ctumS7gZxKcbWWhPTLOUsmG8wH+bhjJy9kz1XUl8cYK2wWwzOcTECfSwHUnNedBUBPpSZFyZzlFb1kzztVogn7pfhZN40APmTxZtLOBxaw/lTY7OM126L2nTYfWxchayiqKoby2kgr4PVOu/Fz4uFEK7p16GbxXYvpVCCmjb0wRz7w61Q2k1JKjLf8A1e0dIPLuHb3HbkKALkzdz8bPF9MY+vNoSzOmHOhtht9nvxbejO2gegqSfQrXRwTDK83T48hrk09W5WSGjY0hX1dWpbjYs3RT5Q1tDpJGNzMBgpsBqC5be4M/+KUZe0ZhLvBlaE2u2blypSFFieKUUHdniQCElOOJaCsK60VtvpTFzyE67jI9Q4Ks78yLzh8oVqokOrMu1mh8+PumHY7Edopo1SgkWpgXX+apinqZhTVieSp2RFv4g/eZF8Dlq9yoM0DWqjFIqTHiAAR1ZfyEEKj+tB9CKeg+pcYA1kPgpEdqiOrNGA1TFo3AB11/H0hEaZmsZqr6QT7UdFQtIzVw/DI7BSRwnW22vaZvMYLdQ6y+4XPliXcaHWg67ZcTL4+9atNGVGR4+cwI/Egk291KkeFrZAGEChRQ95eeR4s6lFkJEcZQFB1yUbmBExInXUh99x9AEez5qaQP795SSEYk3opGpBZigzXEXsteG72pCNvYrUZN1zDzJqqy8p45968Ol6A=
    POSTGRES_USER: AgAanffBcR6jQUmbfke6J9gM6v45VBXNAUtnUtibNPNLSAGDdvxzleC45GraYpP/j+f/487WFDnSagdHAxnDzRJG5QMNGjUbiaz2w14gzr8ni52dndUGTPJr4ZDBtqW5OiCJ3jO9H1rIJMuJglGKfWyL56LYUmTAQZHB+z8exRG9HlO/BLijv+NJHeWOVOYqSgg+S0ji9pNLC4c/+M0rVNeVbEU1GSYJZmLvdN1fNIpfLXl4qlXVo8PWZ8IS5fLaYZRhSRGWFWyLGHNZoG+CJcUssiIV7kc/CKO9XFAQB9iTQU8Q9+CVX9MTB6kyPQ2bAd8v9uf/U43yQimXtqf/ml7qPv0nSw+zFeG96YvU+dkORZsiHHJPMTYgkEv7lJMUPNwmZ0RRuDBuKQOX8f+0D4Xg4eNHs5m4YjxT3eMDiPPd7LguxxcoHQs+1ZruJazQg82RDtgqWWRV8Ei2e3byiUg7wbQHJWyFf0GaBYlehzt6bDrWuXW/65tvyTI/jYVdrVGRPJ6RmXf6lFcQFdDHEfZIVXUZGu/2uu22L+JRNFMquv17j3glkhP4rzJc8qh0OV2KCQRh2XwQ5gRxrWFl3k150iHEW/dNFzzSUslwsKrro0hhzcKWSyeEGPrYwNsy4bOFM6mR//kKzrlImx9Wu756KOVzbZb57Ak8KasLoDV/n3Im+KlGuGPUhCVVk3Yi28PHivq/iTmw
  template:
    metadata:
      name: postgres-api-secret
      namespace: apps
    type: Opaque
