---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-api-secret
  namespace: apps
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCfTNmj3NWIzT7oa4bdDmVmDk2usz0YKRgtKEkZdGm46P9n/VhCzQLld9o7qPtjv3BnY9t2L78NKVVoCi2N8GXdODmVQMDSRuEa6TNf6FwPNbE+47W2wltRwO+zN1UFxAkBgASYc/qwNhYrQ8/BqBPlu4hlmj2tfTk/x8x2PNdgxZ5Tm4/QfWdzadMhDK/FMx3QkA0BbgJUWSQl/C/x/ndbBQdobmXEpHm6Jx55QpiAHXTYUhyPgYzH+Oi+Jg5yXVyv7waf1llfj9VygGrnPkhColeIVzrjHWdNIid+y6hpUwhLOrQygCnsYYHFq9ModYOyhmHqXEvVasVjcQ4vZDERtgaNp+jN7ypfFSXFZNBLTz6r2I0MiBTEL4VCZVVIwipXYrf5NcG9HJ7FS9/3vtnlDVifMHVc4dSUH9XEox+BBUv6rG+8Zn/uzdTtx8G5OlIrtCtlTn+eWGwAVhjTSmOYqQAkMJhl4wL5uq0hWoaTetS+3/5EMvli3Xte2K+/Oz3IYZTyQlTMG4FPog+sNloL9X83SUGs0gAQ7t3BeYRfGixwSi5EugUT+bkB46UkhjYkLwNe5HTF5f0Wlx75MTOHwl3HuG4lIqJKOlpaQ6Wy/IKlf7GzTjUCoaprBjSg0MIAgJErr5oQtxP68ldqjDE5Rf0dm8Hw0AGjldEWS9ojiFGt+K/9Ax/5LX31QoC4RNpxEOgtLvODMHhk
    POSTGRES_USER: AgBtjlj3M/mdcHsg/eDUnS+jUUvFYxEBPE4onQciIQtWJymyLIIc/gmkSWJzWD8BvV8vK0KVI7AuJMpcWQ6z/tERgFtd/PgIipZrJ1zXimIy+ZXriX8PKjsmm/nCmp+q1gDUEF86HVaM23pAsUc7knJciUVY6Ya/gjp+Fwfycoosx19sL2cE3XOJW0Kq1v6PFdPCOPq1N039JtjFkJok/X6gGSQROmRFTbf6hdNFMmmrpuA8++JIYq6TRTI8/3fbSkkGt5v6lsr0JHJfT0Rm8mDOLPgDDLkblJX7QTw/YRgIvcLVg13uFutgWUFKw1vGLLBkCMMlNkcm5Dk+eXxJxhV2w5K7XNPMwY+yGqY6TSmKXTUjtOCaAZm4aW0YOzmDhCo9LISrKFZL15x795P/vqGU5n+FTOVo9/JtMbN1IaxzSn39Aw/aS86uUC1Zvv29z99L484VWk4rJKGGM5NhnbDEMmHTQUceo+T9zO15K7xtt57DlP66k0BkXVqVcKMzXQ78qhDFtIhh+PEbxzldxcytNcY3BK+q/J38whbgfCbDpBvIvkC4ldmjXJ4Z+v0JfUOtTkXaW/qiduDokNI/Ot3SuP+7PKT9dLAffDbpxTeZXrxzOrOfjZEk8eNvvFPdnXe5TV8UPYQ3S4bVUVPu037+9YHMiYvef8ng1rdXnFv/laQMySzIj/sQaFugXNBVyCLHbQdAmb5r
  template:
    metadata:
      labels:
        app: postgres-api
        environment: lab
        team: platform
      name: postgres-api-secret
      namespace: apps
    type: Opaque
