apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: postgres-api
  namespace: apps
spec:
  hosts: [nginx.lab.local]
  gateways: [nginx-lab/nginx-lab-gateway]
  http:
    - name: primary
      match:
        - uri: {prefix: /postgres-api}
      rewrite:
        uriRegexRewrite:
          match: ^/postgres-api(/|$)(.*)
          rewrite: /\2
      route:
        - destination:
            host: postgres-api-stable.apps.svc.cluster.local
            port: {number: 80}
          weight: 100
        - destination:
            host: postgres-api-canary.apps.svc.cluster.local
            port: {number: 80}
          weight: 0