apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: postgres-api
  namespace: apps
spec:
  targetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: postgres-api
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: postgres-api
        controlledResources:
          - cpu
          - memory
        minAllowed:
          cpu: 25m
          memory: 64Mi
        maxAllowed:
          cpu: 500m
          memory: 512Mi
