apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-worker
  namespace: workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-worker
  template:
    metadata:
      labels:
        app: cpu-worker
    spec:
      containers:
        - name: cpu-worker
          image: ghcr.io/gefmoura0601-bot/cpu-worker-go:latest
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_URL
              value: amqp://admin:admin123@rabbitmq.messaging.svc.cluster.local:5672/
            - name: QUEUE_NAME
              value: cpu-jobs
            - name: WORK_SECONDS
              value: "8"
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "1000m"
              memory: "128Mi"
