apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: workers-rabbitmq
  namespace: workers
spec:
  encryptedData:
    RABBITMQ_URL: AgARx2X0c123oD+WW6jhNjnxzRE0HIlQqQJ+gFzIUobkS3YuvqPXD3BUvMM1oNA5dJqJRur8s65jsqrlNgeXVhyK2MNKmNqW4NhaGKAyw771qT+lA5yFa4JPABmE5dNrbdgyeOY+kvk1tqtmV2qAzi6L1bOqPWOTW/F6KHZfl7yxZBm1mdVlWNqoSievnBuOwnG0c8WoDy9e76F5paVnR3gs5QoxqTzE1h9YQvVZ8dCIYpthUZwwxn3rCMhz2xzg6gxE621JSfwgIGNy5RQSk3MmkjRW60B1i2gGeroDP95S73eNzMfKzGEcYAAdN53H0vu8n/VZyNliFgB36UGJr5DS62Qt+xf/Rz84JNeHtLr/9HYcV45mcB4iyfvWHz50LVL5FUhdsP9qqaYaiF4FKujHarsnN0/Tg46CEwKvYAgvoGaFKbMqZ9RMMZoPkCSJ4CgcHK/r73mPYJwtS2w0sBGT1g2fw8YdiR1SgiNMgx6sDUcRiEFtM+Ffb5Q+Ne28CHNcqJG+IjCrw5UhpeUD4ndsjtrK79zDa0ez9wNkEpqSKvundBuzvC9wTx28LTF0A+OxN2pI3A+XPgz5rYNEXlhxmbqubjBy/dP4CQqQGAR/7CP4wcLzAb2dEXXEJauIcn7gH/6ELsrBxCr2H/LX6MZ4vZllBDtOswtMgp8bYELTtMFz+9r7STVcZHLeOBFl04pqfOTj09kbXDRIWLw63R6Y+gU+ZrVcBk2FxaT+Md9URN3x7NabeVpQJ1w1+wr/3xFzgPpkmfzgZ777VQDAmxxoi32en/3+Tb7+LGj/BWALS8UuLe4ldL1FO9b2tKcyf2EAcTYCwn2uYQlG
  template:
    metadata:
      name: workers-rabbitmq
      namespace: workers
    type: Opaque
