---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: workers-rabbitmq
  namespace: workers
spec:
  encryptedData:
    RABBITMQ_URL: AgAWAz+Erz/zS/DE7daM9FsMUlWzgimVdMdDWuKnBok1WFlGHR63O3fVpnfnMAbOQEVCcXzvTm7/ldA52yEQqdJm1qPZvfugsZmYHfHngiPswTKub3riI5/rWkZ0/mQUxuyI00ORX8ChVKr0+3k9ktoSfaiYRs50kwzOQxi2DGIExO3mp/ZmzcHFei4SQxkvu4AOIbkf/fVOi/mXD1hYiNlANJh4HAYvdcHLKfQ+Vri40Rmp9zrZZVvs78X5Fl9KB3l6XHlvd6JTqjQyHbiHHRuS8x5hv2fYiZzueiG+lFwZsUtwfqdd8/l81rHrMSpNMyXQ3ICQavBrNZZ+Xbc4NSkNhI/f1wcvk/ThGsDLGsFjv4SIXbtOCK57D1GNMK6a/hXtcMMtiSAVqkPoFB2zKBCoVW69T9pCUeu3S5e2PBThi2Y3WEQpO/Xe8rOk+qcW0PEUK6NYn6Vu7A6/WLxHcPSjbhdG0ycge1t0v1XkPsa0abhJxkL2slEYikyZsJjKAiSkaEz/C+LbIaJEh2ww7l7vY3HvDlZDsloaYUrHAAncOloq2x96cn2SfS0kgxeJ4yZJV4RZQ/Zxv85XpTdQqfKzC1yB9mNe4BlCiQSJKdjyXPEdRGiDxVV15/RGULmUwvYFzW+eOXIXkhYbstdYJJLwqOV25x2V0Dwn8ZryUNEn+q0/lYe4ISPtryfCRW1wk1QRmhwVW+8A6UyE7pTDqwed607m7dfCUUIH/OPknjx04/SUJuoIebkAqYst6w8AbjDOiRuyh37AIMGsGQ9OVI8Z
  template:
    metadata:
      name: workers-rabbitmq
      namespace: workers
    type: Opaque
