apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: calico-typha
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - calico-system
  selector:
    matchLabels:
      k8s-app: calico-typha-metrics
  endpoints:
    - port: calico-typha-metrics
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
