apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-standard-labels
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-standard-labels
      match:
        any:
          - resources:
              namespaces:
                - apps
                - workers
              kinds:
                - Pod
                - Service
                - Deployment
                - StatefulSet
                - DaemonSet
                - Job
                - CronJob
                - ConfigMap
                - Secret
                - PersistentVolumeClaim
      exclude:
        any:
          - resources:
              kinds:
                - ConfigMap
              names:
                - kube-root-ca.crt
                - istio-ca-crl
                - istio-ca-root-cert
      skipBackgroundRequests: true
      validate:
        allowExistingViolations: true
        message: Os labels app, team e environment são obrigatórios.
        pattern:
          metadata:
            labels:
              app: "?*"
              team: "?*"
              environment: "?*"
