apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-probes
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-probes
      match:
        any:
          - resources:
              namespaces:
                - apps
                - workers
              kinds:
                - Pod
      skipBackgroundRequests: true
      validate:
        message: Todos os containers da aplicação devem definir readinessProbe e livenessProbe.
        allowExistingViolations: true
        foreach:
          - list: "request.object.spec.containers"
            preconditions:
              all:
                - key: "{{ element.name }}"
                  operator: NotEquals
                  value: istio-proxy
            pattern:
              name: "*"
              readinessProbe:
              livenessProbe:
