name: CPU Producer Image CI

on:
  push:
    branches:
      - main
    paths:
      - 'app/cpu-producer-go/**'
      - '.github/workflows/cpu-producer-image-ci.yaml'

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Normalize owner
        id: owner
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Set image tag
        id: vars
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: ./app/cpu-producer-go
          push: true
          tags: ghcr.io/${{ steps.owner.outputs.owner_lc }}/cpu-producer-go:${{ steps.vars.outputs.tag }}

      - name: Update GitOps manifest with new tag
        run: |
          sed -i 's|image: ghcr.io/.*/cpu-producer-go:.*|image: ghcr.io/${{ steps.owner.outputs.owner_lc }}/cpu-producer-go:${{ steps.vars.outputs.tag }}|' kubernetes/apps/workers/cpu-producer/deployment.yaml
          grep 'image:' kubernetes/apps/workers/cpu-producer/deployment.yaml

      - name: Commit manifest update
        if: ${{ false }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add kubernetes/apps/workers/cpu-producer/deployment.yaml

          if git diff --cached --quiet; then
            echo "Sem mudanças para commit."
            exit 0
          fi

          git commit -m "ci: update cpu-producer image tag to ${{ steps.vars.outputs.tag }}"
          git push

      - name: Create GitOps update PR
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
        with:
          commit-message: "ci: update cpu-producer image tag to ${{ steps.vars.outputs.tag }}"
          branch: "automation/cpu-producer-${{ steps.vars.outputs.tag }}"
          delete-branch: true
          title: "ci: update cpu-producer image to ${{ steps.vars.outputs.tag }}"
          body: "Automated GitOps image update generated by CPU Producer Image CI."
          add-paths: kubernetes/apps/workers/cpu-producer/deployment.yaml
