name: Deploy K8s Lab Local (VMware)

on:
  push:
    branches: [ "main" ]

jobs:
  k8s-deploy:
    runs-on: [self-hosted, master] 

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Validar Conexão com Cluster
        run: kubectl get nodes

      - name: Deploy Nginx no PRD
        run: |
          # Aplica o manifesto do Nginx com storage XFS/LVM
          kubectl apply -f k8s/prd/nginx-enterprise.yaml
          
      - name: Verificar Status do Deploy
        run: kubectl get pods -n prd
